# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

environment_variables:
- "YOLO_DATASETS_DIR=/ryzers/data_ultralytics"
- "YOLO_CONFIG_DIR=/ryzers"

volume_mappings:
- "$PWD/data_ultralytics:/ryzers/data_ultralytics" 
