#!/bin/bash

docker run --rm       -p 9091:9091 -p 9092:9092 -p 9093:9093       --network flwr-network   --shm-size 16G --cap-add=SYS_PTRACE  --network=ryzers --ipc=host --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --group-add render  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/video0 --device /dev/video1    --name superlink       --detach       superlink       --insecure       --isolation       process

docker run --rm     -p 9095:9095     --network flwr-network     --name supernode-2     --detach     --shm-size 16G --cap-add=SYS_PTRACE  --network=ryzers --ipc=host --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --group-add render  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/video0 --device /dev/video1 supernode      --insecure     --superlink superlink:9092     --node-config "partition-id=0 num-partitions=2"     --clientappio-api-address 0.0.0.0:9095     --isolation process

docker run --rm     -p 9094:9094     --network flwr-network     --name supernode-1     --detach     --shm-size 16G --cap-add=SYS_PTRACE  --network=ryzers --ipc=host --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --group-add render  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/video0 --device /dev/video1 supernode      --insecure     --superlink superlink:9092     --node-config "partition-id=0 num-partitions=2"     --clientappio-api-address 0.0.0.0:9094     --isolation process

docker run --rm     --network flwr-network     --name superexec-serverapp     --detach     --shm-size 16G --cap-add=SYS_PTRACE  --network=ryzers --ipc=host --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --group-add render  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/video0 --device /dev/video1 superexec     --insecure     --plugin-type serverapp     --appio-api-address superlink:9091

docker run --rm     --network flwr-network     --name superexec-clientapp-1     --shm-size 16G --cap-add=SYS_PTRACE  --network=ryzers --ipc=host --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --group-add render  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/video0 --device /dev/video1 --detach     superexec     --insecure     --plugin-type clientapp     --appio-api-address supernode-1:9094

docker run --rm     --network flwr-network     --name superexec-clientapp-2     --shm-size 16G --cap-add=SYS_PTRACE  --network=ryzers --ipc=host --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --group-add render  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/video0 --device /dev/video1 --detach     superexec     --insecure     --plugin-type clientapp     --appio-api-address supernode-2:9095
