# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

volume_mappings:
- "$PWD/lmstudio_models:/root/.lmstudio/models/"  

port_mappings:  
 - "1234:1234"
 - "5900:5900"
